server:
  port: 10000

spring:
  application:
    name: basic
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: scott
    password: 1234
  jpa:
    databasePlatform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddlAuto: create
#      ddlAuto: create-drop
#      ddlAuto: update
#      ddlAuto: validate
    properties:
      hibernate:
        use_sql_comments: true # 생성된 jpql을 콘솔에 띄워준다.

